apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-deployment
  namespace: default  # Must match your Fargate profile namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
        - name: brain-tasks-container
          image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
          ports:
            - containerPort: 3000
