apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  namespace: default  # Must match your Fargate profile namespace
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks
  ports:
    - protocol: TCP
      port: 80        # External port exposed
      targetPort: 3000  # Port your app listens on
